Projek_UTSAren/Models/Alumni.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Projek_UTSAren.Models
{
    public class Alumni
    {
        [Key]
        public string NIM { get; set; }
        [Required]
        public string Nama_alumni { get; set; }
        [Required]
        public int Tahun_angkatan { get; set; }
        [Required]
        public string Jenis_kelamin { get; set; }
        [Required]
        public string Tempat_lahir { get; set; }
        [Required]
        public DateTime Tanggal_lahir { get; set; }
        [Required]
        public string Pekerjaan { get; set; }
        [Required]
        public string Alamat { get; set; }
        [Required]
        public string Telp { get; set; }
        public string Foto { get; set; }
        public Roles Roles { get; set; }
    }

}

Projek_UTSAren/Areas/Admin/Controllers/AlumniController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Projek_UTSAren.Data;
using Projek_UTSAren.Models;
using Projek_UTSAren.Services.AlumniService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Projek_UTSAren.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AlumniController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IAlumniService _alumniService;
        public AlumniController(AppDbContext context, IAlumniService alumni)
        {
            _context = context;
            _alumniService = alumni;
        }
        public IActionResult Index()
        {
            var data = _context.Tb_Alumni.ToList();
            return View(data);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Alumni alumni, IFormFile Image)
        {
            if (ModelState.IsValid)
            {
                _alumniService.CreateAlumni(alumni, Image);

                return RedirectToAction("Index");
            }
            return View(alumni);
        }
        public IActionResult Update(string id)
        {
            var cari = _alumniService.AmbilAlumniBerdasarkanId(id);

            if (cari != null)
            {
                return View(cari);
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult Update(Alumni ubah, IFormFile Image)
        {
            if (ModelState.IsValid)
            {
                var cari = _alumniService.AmbilAlumniBerdasarkanId(ubah.NIM);
                if (cari != null)
                {
                    _alumniService.UpdateAlumni(ubah, Image);
                    return Redirect("/Admin/Alumni/Detail/" + ubah.NIM);

                }
                return NotFound(0);
            }
            return View(ubah);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var cari = _context.Tb_Alumni.Where(x => x.NIM == id).FirstOrDefault();
            if (cari == null)
            {
                return NotFound();
            }
            _context.Tb_Alumni.Remove(cari);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        public IActionResult Detail(string id)
        {
            Alumni cari = _alumniService.AmbilAlumniBerdasarkanId(id);

            if (cari != null)
            {
                return View(cari);
            }
            return NotFound();
        }
    }
}

Projek_UTSAren/Areas/User/Controllers/AlumniController.cs
using Microsoft.AspNetCore.Mvc;
using Projek_UTSAren.Data;
using Projek_UTSAren.Models;
using Projek_UTSAren.Services.AlumniService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Projek_UTSAren.Areas.User.Controllers
{
    [Area("User")]
    public class AlumniController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IAlumniService _alumniService;
        public AlumniController(AppDbContext context, IAlumniService alumni)
        {
            _context = context;
            _alumniService = alumni;
        }
        public IActionResult Index()
        {
            var data = _context.Tb_Alumni.ToList();
            return View(data);
        }
        public IActionResult Detail(string id)
        {
            Alumni cari = _alumniService.AmbilAlumniBerdasarkanId(id);

            if (cari != null)
            {
                return View(cari);
            }
            return NotFound();
        }
    }
}

Projek_UTSAren/Areas/Admin/Views/Alumni/Create.cshtml
@model Alumni

@{ Layout = "_LayoutAkun"; }

@{ ViewData["Title"] = "Create"; }

<h2 style="text-align:center">Tambah</h2>

<h4 style="text-align:center">Data Alumni</h4>
<hr />
<div class="row">
    <div class="card-body">
        <form asp-action="Create" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="NIM" class="control-label"></label>
                <input asp-for="NIM" class="form-control" />
                <span asp-validation-for="NIM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nama_alumni" class="control-label"></label>
                <textarea asp-for="Nama_alumni" class="form-control"></textarea>
                <span asp-validation-for="Nama_alumni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tahun_angkatan" class="control-label"></label>
                <input asp-for="Tahun_angkatan" class="form-control" />
                <span asp-validation-for="Tahun_angkatan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Jenis_kelamin" class="control-label"></label>
                <input asp-for="Jenis_kelamin" class="form-control" />
                <span asp-validation-for="Jenis_kelamin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tempat_lahir" class="control-label"></label>
                <input asp-for="Tempat_lahir" class="form-control" />
                <span asp-validation-for="Tempat_lahir" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tanggal_lahir" class="control-label"></label>
                <input asp-for="Tanggal_lahir" class="form-control" />
                <span asp-validation-for="Tanggal_lahir" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pekerjaan" class="control-label"></label>
                <input asp-for="Pekerjaan" class="form-control" />
                <span asp-validation-for="Pekerjaan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alamat" class="control-label"></label>
                <textarea asp-for="Alamat" class="form-control"></textarea>
                <span asp-validation-for="Alamat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telp" class="control-label"></label>
                <input asp-for="Telp" class="form-control" />
                <span asp-validation-for="Telp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Foto"></label>
                <input type="file" name="Image" accept=".jpg,.png,.jpeg" class="form-control" multiple />
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Simpan" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a class="btn btn-dark" style="color:white" asp-area="Admin" asp-action="Index">Kembali</a>
</div>
<br />
<br />

Projek_UTSAren/Areas/Admin/Views/Alumni/Detail.cshtml
@model Alumni

@{ Layout = "_LayoutAdmin"; }

@{ ViewData["Title"] = "Detail"; }

<br />
<h2>Detail Alumni</h2>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NIM)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NIM)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nama_alumni)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nama_alumni)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tahun_angkatan)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tahun_angkatan)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Jenis_kelamin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Jenis_kelamin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tempat_lahir)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tempat_lahir)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tanggal_lahir)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tanggal_lahir)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pekerjaan)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pekerjaan)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Alamat)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Alamat)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telp)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telp)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.Foto" width="100" alt="Alternate Text" />
        </dd>
    </dl>
</div>
<br />
<br />
<div>
    <a class="btn btn-dark" style="color:white" asp-action="Update" asp-route-id="@Model.NIM">Edit</a>
    <a class="btn btn-dark" style="color:white" asp-action="Index">Kembali</a>
</div>
@section Scripts {
<script>$(document).ready(function () {
            $('#tb-datatable').DataTable(
                {
                    dom: 'Bfrtip',
                    buttons: [
                        'print',
                    ]
                }
            );
        });</script>
}

Projek_UTSAren/Areas/Admin/Views/Alumni/Index.cshtml
@model IEnumerable<Alumni>

@{ Layout = "_LayoutAdmin"; }

@{ ViewData["Title"] = "Index"; }

<br />
<br />
<p>
    <a class="btn btn-info" asp-controller="Alumni" asp-action="Create">Tambah</a>
</p>

<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Data Alumni
    </div>
    <div class="card-body">
        <table class="table" id="tb-datatable">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.NIM)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nama_alumni)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Tahun_angkatan)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Jenis_kelamin)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Tempat_lahir)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Tanggal_lahir)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Pekerjaan)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Alamat)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Telp)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NIM)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nama_alumni)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tahun_angkatan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Jenis_kelamin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tempat_lahir)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tanggal_lahir)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pekerjaan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Alamat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telp)
        </td>
        <td>
            <a class="btn btn-info" style="color:white" asp-action="Update" asp-route-id="@item.NIM">Edit</a>
            <a class="btn btn-dark" style="color:white" asp-action="Detail" asp-route-id="@item.NIM">Detail</a>
            <a class="btn btn-info" style="background-color:red" asp-action="Delete" asp-route-id="@item.NIM" onclick="if (!confirm('Yakin Ingin Hapus?')) { return false;}">Hapus</a>
        </td>
    </tr>
}
            </tbody>
        </table>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#tb-datatable').DataTable(
                {
                    dom: 'Bfrtip',
                    buttons: [
                        'print',
                    ]
                }
            );
        });
    </script>
}

Projek_UTSAren/Areas/Admin/Views/Alumni/Update.cshtml
@model Alumni

@{ Layout = "_LayoutAkun"; }

@{ ViewData["Title"] = "Update"; }

<br />
<h2 style="text-align:center">Edit</h2>

<h4 style="text-align:center">Data Alumni</h4>
<hr />
<div class="row">
    <div class="card-body">
        <form asp-action="Update" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="NIM" />
                <div class="form-group">
                    <label asp-for="Nama_alumni" class="control-label"></label>
                    <textarea asp-for="Nama_alumni" class="form-control"></textarea>
                    <span asp-validation-for="Nama_alumni" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Tahun_angkatan" class="control-label"></label>
                    <input asp-for="Tahun_angkatan" class="form-control" />
                    <span asp-validation-for="Tahun_angkatan" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Jenis_kelamin" class="control-label"></label>
                    <input asp-for="Jenis_kelamin" class="form-control" />
                    <span asp-validation-for="Jenis_kelamin" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Tempat_lahir" class="control-label"></label>
                    <input asp-for="Tempat_lahir" class="form-control" />
                    <span asp-validation-for="Tempat_lahir" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Tanggal_lahir" class="control-label"></label>
                    <input asp-for="Tanggal_lahir" class="form-control" />
                    <span asp-validation-for="Tanggal_lahir" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Pekerjaan" class="control-label"></label>
                    <input asp-for="Pekerjaan" class="form-control" />
                    <span asp-validation-for="Pekerjaan" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Alamat" class="control-label"></label>
                    <textarea asp-for="Alamat" class="form-control"></textarea>
                    <span asp-validation-for="Alamat" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Telp" class="control-label"></label>
                    <input asp-for="Telp" class="form-control" />
                    <span asp-validation-for="Telp" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Foto" class="control-label"></label>
                    <input asp-for="Foto" type="hidden" />
                    <img src="@Model.Foto" width="100" alt="Alternate Text" />
                    <input type="file" name="Image" class="form-control" accept=".jpg,.png,.jpeg" multiple />
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-primary" />
                </div>
</form>
    </div>
</div>
<div>
    <a class="btn btn-dark" style="color:white" asp-area="Admin" asp-action="Index">Kembali</a>
</div>
<br />
<br />
<br />